services:
  client:
    image: zhandongliulab/marrvel-client
    volumes:
      - "${LOCAL_BASE}/dist:/output"
    command: sh -c "cp -r dist/* /output/"

  server:
    image: zhandongliulab/marrvel-server
    working_dir: /MARRVEL/server
    volumes:
      - "${LOCAL_BASE}/.env:/MARRVEL/server/.env"
      - "${LOCAL_BASE}/dist:/MARRVEL/dist"
      - "${LOCAL_BASE}/config:/tmp/config"
      - "${LOCAL_BASE}/transvar.download:/root/.transvar.download"
    ports:
      - "8080:8080"
    command: sh -c "cp -r /tmp/config/* /MARRVEL/server/config/ && npm start"
