export const CATEGORIES = [
  { id: 1, name: 'Prenatal Development or Birth' },
  { id: 2, name: 'Growth Abnormality' },
  { id: 3, name: 'Nervous System' },
  { id: 4, name: 'Eye and Ear' },
  { id: 5, name: 'Integument' },
  { id: 6, name: 'Head and Neck' },
  { id: 7, name: 'Limb/Appendage' },
  { id: 8, name: 'Skeletal and Connective Tissue' },
  { id: 9, name: 'Blood and Immune' },
  { id: 10, name: 'Cardiovascular' },
  { id: 11, name: 'Musculature' },
  { id: 12, name: 'Respiratory' },
  { id: 13, name: 'Digestive' },
  { id: 14, name: 'Genitourinary' },
  { id: 15, name: 'Endocrine' },
  { id: 16, name: 'Metabolism/Homeostasis' },
  { id: 17, name: 'Neoplasm' },
  { id: 18, name: 'Other' }
];
export const CAT_TO_ICON = {
  'Prenatal Development or Birth': 'prenatal',
  'Growth Abnormality': 'growth',
  'Nervous System': 'nervous_system',
  'Eye and Ear': 'eye_and_ear',
  'Integument': 'integument',
  'Head and Neck': 'head',
  'Limb/Appendage': 'appendages',
  'Skeletal and Connective Tissue': 'skeletal',
  'Blood and Immune': 'blood',
  'Cardiovascular': 'cardiovascular',
  'Musculature': 'musculature',
  'Respiratory': 'respiratory',
  'Digestive': 'digestive',
  'Genitourinary': 'genitourinary',
  'Endocrine': 'endocrine',
  'Metabolism/Homeostasis': 'metabolism',
  'Neoplasm': 'neoplasm',
  'Other': 'etc'
};

export const HPO_BROAD_TO_CAT = {
  'HP:0000924': 'Skeletal and Connective Tissue',
  'HP:0040064': 'Limb/Appendage',
  'HP:0000707': 'Nervous System',
  'HP:0000152': 'Head and Neck',
  'HP:0001939': 'Metabolism/Homeostasis',
  'HP:0001626': 'Cardiovascular',
  'HP:0000478': 'Eye and Ear',
  'HP:0001574': 'Integument',
  'HP:0000119': 'Genitourinary',
  'HP:0002715': 'Blood and Immune',
  'HP:0025031': 'Digestive',
  'HP:0002664': 'Neoplasm',
  'HP:0003011': 'Musculature',
  'HP:0001871': 'Blood and Immune',
  'HP:0000818': 'Endocrine',
  'HP:0002086': 'Respiratory',
  'HP:0000598': 'Eye and Ear',
  'HP:0025354': 'Other',
  'HP:0003549': 'Skeletal and Connective Tissue',
  'HP:0001197': 'Prenatal Development or Birth',
  'HP:0001507': 'Growth Abnormality',
  'HP:0025142': 'Growth Abnormality',
  'HP:0000769': 'Other',
  'HP:0001608': 'Other',
  'HP:0045027': 'Skeletal and Connective Tissue',
  'HP:0001438': 'Digestive'
};
