type: object
properties:
  entrezId: integer
  ensemblId: string
  syn:
    required: false
    type: object
    description: Synonymous
    properties:
      exp:
        type: number
        description: Expected variant counts
      obs:
        type: number
        description: Number of unique variants observed
      z: number
      oe:
        type: number
        description: o/e score
      oeLower:
        type: number
        description: Lower bound of o/e score
      oeUpper:
        type: number
        description: Upper bound of o/e score

  mis:
    required: false
    type: object
    description: Missense
    properties:
      exp:
        type: number
        description: Expected variant counts
      obs:
        type: number
        description: Number of unique variants observed
      z: number
      oe:
        type: number
        description: o/e score
      oeLower:
        type: number
        description: Lower bound of o/e score
      oeUpper:
        type: number
        description: Upper bound of o/e score

  lof:
    required: false
    type: object
    properties:
      exp:
        type: number
        description: Expected variant counts
      obs:
        type: number
        description: Number of unique variants observed
      z: number
      pLI: number
      oe:
        type: number
        description: o/e score
      oeLower:
        type: number
        description: Lower bound of o/e score
      oeUpper:
        type: number
        description: Upper bound of o/e score
