type: object
properties:
  mimNumber:
    type: integer
  phenotype: string
  phenotypeMimNumber:
    type: integer
    description: Mim number of the phenotype
  phenotypicSeriesNumber:
    type: string
    description: Comma delimited list of phenotypic series numbers
  phenotypeMappingKey:
    type: integer
  phenotypeInheritance: string
